### ISSUE TITLE
how can i send photo ?

### ISSUE THREAD

**Issue by shayanzare** [moritzsternemann/QtTelegramBot#2]
Hello.

how can i send photo?

**Comment by moritzsternemann** [comment]
Hey :)

Use the `Bot::sendPhoto(<chatId>, <file OR fileId>, ...)`
Where *file* is a `QFile` pointer or *fileId* is the ID of a already uploaded file.

**Comment by shayanzare** [comment]
@moritzsternemann thanks bro

**Comment by shayanzare** [comment]
@moritzsternemann 
Hello :)

when i run project show this error :

> 
> /root/Desktop/QtTelegramBot/examples/echo/main.cpp:63: error: no matching function for call to 'Telegram::Bot::sendPhoto(qint32&, QFile&)'
>                  bot->sendPhoto(message.chat.id, file);
>                                                       ^
> 

This is my code :

```cpp
            QFile file("~/screenshot.png");
            if (file.open(QIODevice::ReadOnly)) {
                bot->sendPhoto(message.chat.id, file);
            }
            else
            {
                qDebug() << "Error to opening file";
            }
```

**Comment by lordmahan** [comment]
Hi shayan
you can use this:
`bot->sendPhoto(message.chat.id, &file);`
look at the `&`
it worked for me :D
